# Первый этап: сборка фронтенда
FROM node:18-alpine as frontend

WORKDIR /app
COPY ./tale-gameshop/package*.json ./
RUN npm ci
COPY ./tale-gameshop .
RUN npm run build -- --env appConfigEnv=docker

# Второй этап: настройка Nginx
FROM nginx:alpine

# Копируем конфиг для Nginx в контейнер
COPY nginx.conf /etc/nginx/nginx.conf

# Копируем собранные фронтенд-ресурсы из первого этапа
COPY --from=frontend /app/dist /usr/share/nginx/html

# Открываем порт 80 для Nginx
EXPOSE 80

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]
