namespace SuperBot.WebApi.Mail;

public static partial class MailTexts
{
    // Английский — эталон: набор ключей остальных языков обязан совпадать с ним (см. MailTextsTests).
    private static readonly Dictionary<string, string> En = new()
    {
        ["date.long"] = "d MMMM yyyy",
        ["layout.tagline"] = "Tale Shop · Game keys, delivered.",

        ["common.needHelp"] = "Need help?",
        ["common.questions"] = "Questions?",
        ["common.contactSupport"] = "Contact support",

        // Подтверждение почты при гостевой покупке.
        ["verify.subject"] = "Confirm your email to receive your keys — order {0}",
        ["verify.text"] = "Thanks for your purchase at {0}!\n\nOrder {1} is paid. To receive your game keys, confirm this email address:\n\n{2}\n\nThe link is valid for 48 hours. If you didn't make this purchase, ignore this email.",
        ["verify.heading"] = "One step left",
        ["verify.lead"] = "Order {0} is paid. Confirm this email address and your keys land in this inbox instantly.",
        ["verify.button"] = "Confirm email & get my keys",
        ["verify.footer"] = "The link is valid for 48 hours. If you didn't make this purchase, you can safely ignore this email.",

        // Письмо с ключами.
        ["keys.subjectPartial"] = "Part of your order is ready — order {0}",
        ["keys.subjectSoftware"] = "Your software keys — order {0}",
        ["keys.subjectGame"] = "Your game keys — order {0}",
        ["keys.subject"] = "Your keys — order {0}",
        ["keys.progress_one"] = "{1} of {0} key",
        ["keys.progress_other"] = "{1} of {0} keys",
        ["keys.textPartial"] = "Part of order {0} is ready ({1}):",
        ["keys.textIntro"] = "Your keys for order {0}:",
        ["keys.textSoftwareLine"] = "{0}: {1} — activate on {2}",
        ["keys.textPendingHeader"] = "Still on the way:",
        ["keys.pendingNote"] = "We'll email these automatically as soon as we restock.",
        ["keys.textGuide"] = "Activation guide: see the Keys & activation page in your account, or the activation guide on the site.",
        ["keys.activateOn"] = "Activate on {0}",
        ["keys.buttonSoftware"] = "How to activate your software",
        ["keys.buttonGame"] = "How to activate your key",
        ["keys.linkSoftware"] = "Activating software keys",
        ["keys.headingPartial"] = "Part of your order is ready",
        ["keys.headingMany"] = "Your keys are ready",
        ["keys.headingOne"] = "Your key is ready",
        ["keys.leadPartial"] = "Order {0} — <strong>{1}</strong> are ready. Here's what's ready now; the rest arrives automatically as soon as we restock.",
        ["keys.leadSoftwareMany"] = "Order {0} is complete. <strong>Your licence keys are below</strong> — activate with the vendor as shown under each key.",
        ["keys.leadSoftwareOne"] = "Order {0} is complete. <strong>Your licence key is below</strong> — activate with the vendor as shown under the key.",
        ["keys.leadMixed"] = "Order {0} is complete. <strong>Your keys are below</strong> — each one shows where to activate it.",
        ["keys.leadGame"] = "Order {0} is complete. <strong>Your game key is below</strong> — redeem it on the store to start playing.",
        ["keys.pendingTitle"] = "Still on the way",
        ["keys.footer"] = "Keep this email safe — treat keys like cash. We can't recover a key once it's been used.",
        ["keys.cashbackText"] = "Cashback: +{0} ({1}%) is on its way to your balance",
        ["keys.cashbackTextFrom"] = " and can be spent from {0}.",
        ["keys.cashbackTextNow"] = " and can be spent now.",
        ["keys.cashbackFrom"] = "Ready to spend from {0}",
        ["keys.cashbackNow"] = "Ready to spend now",
        ["keys.cashbackLink"] = "My cashback",
        ["keys.cashbackEarned"] = "Cashback earned",
        ["keys.cashbackOfOrder"] = "{0}% of your order",
        ["place.microsoft"] = "your Microsoft account",
        ["place.app"] = "the app",
        ["place.vendor"] = "the vendor's website",

        // Авто-возврат: почта не подтверждена.
        ["autorefund.subject"] = "Order {0} was refunded — email not confirmed",
        ["autorefund.text"] = "We didn't receive a confirmation of this email address within 48 hours, so order {0} was cancelled and fully refunded.\n\nThe money returns to your card, usually within 5–10 business days.\n\nIf you still want the game, just place the order again — and confirm the email right away.",
        ["autorefund.heading"] = "Order refunded",
        ["autorefund.lead"] = "We didn't get a confirmation of this email within 48 hours, so order {0} was cancelled and <strong>fully refunded</strong>. The money returns to your card, usually within 5–10 business days.",
        ["autorefund.button"] = "Browse the store",
        ["autorefund.footer"] = "Still want the game? Place the order again and confirm the email right away.",

        // Возврат магазином.
        ["refund.subjectFull"] = "Order {0} was refunded",
        ["refund.subjectPart"] = "Part of order {0} was refunded",
        ["refund.textFull"] = "We've refunded order {0}.",
        ["refund.textPart"] = "We've refunded part of order {0}. The rest of the order stays as it is.",
        ["refund.refundedList"] = "Refunded:",
        ["refund.refundedTitle"] = "Refunded",
        ["refund.backWayPaid"] = "Back the way you paid",
        ["refund.toCard"] = "To your card",
        ["refund.toPaidWith"] = "To your {0}",
        ["refund.textCardArrives"] = "{0}: {1} — usually arrives within 5–10 business days.",
        ["refund.textPlain"] = "{0}: {1}.",
        ["refund.textCashback"] = "To your cashback balance: {0} — available right away.",
        ["refund.toCashback"] = "To your cashback balance",
        ["refund.underCent"] = "The refunded amount is under one cent, so nothing moves on your card.",
        ["refund.questions"] = "Questions about the refund? Just reply to this email.",
        ["refund.headingFull"] = "Order refunded",
        ["refund.headingPart"] = "Part of your order refunded",
        ["refund.cardArrives"] = "Card refunds usually arrive within 5–10 business days.",
        ["refund.button"] = "My cashback",

        // Уведомления о кэшбэке.
        ["cbnotice.availableSubject"] = "{0} of cashback is ready to use",
        ["cbnotice.expiryLine"] = "Cashback is valid for a limited time: the earliest part expires on {0}.",
        ["cbnotice.availableText"] = "{0} of cashback from your orders has finished its waiting period and is now on your balance.",
        ["cbnotice.availableToSpend"] = "Available to spend: {0}.",
        ["cbnotice.howToUseText"] = "To use it, switch on \"Pay with cashback\" at checkout. It can cover your whole order except a small minimum paid by card.",
        ["cbnotice.yourCashback"] = "Your cashback: {0}",
        ["cbnotice.unsubscribeText"] = "Do not want emails about cashback? {0}",
        ["cbnotice.availableHeading"] = "Your cashback is ready",
        ["cbnotice.availableLead"] = "<strong>{0}</strong> from your orders has finished its waiting period and can be spent now.",
        ["cbnotice.nowAvailable"] = "Now available to spend",
        ["cbnotice.howToUseNote"] = "Switch on “Pay with cashback” at checkout. It can cover your whole order except a small minimum paid by card.",
        ["cbnotice.button"] = "See my cashback",
        ["cbnotice.expiringSubject"] = "{0} of your cashback expires on {1}",
        ["cbnotice.expiringText"] = "{0} of your cashback expires on {1}. After that date it is removed from your balance.",
        ["cbnotice.availableNowText"] = "Available to spend right now: {0}.",
        ["cbnotice.oldestFirstText"] = "Cashback is always spent oldest first, so using any of it at checkout before that date uses the expiring part.",
        ["cbnotice.expiringHeading"] = "Some cashback expires soon",
        ["cbnotice.expiringLead"] = "<strong>{0}</strong> of your cashback expires on <strong>{1}</strong>. After that it is removed from your balance.",
        ["cbnotice.expiresOn"] = "Expires {0}",
        ["cbnotice.availableNow"] = "Available to spend now",
        ["cbnotice.oldestFirstNote"] = "Cashback is spent oldest first, so paying with it at checkout before that date uses the expiring part.",
        ["cbnotice.footerReason"] = "You are getting this because you have a cashback balance at our store.",
        ["cbnotice.footerStop"] = "Stop cashback emails",

        // Брошенная корзина.
        ["cart.subjectOne"] = "{0} is still in your cart",
        ["cart.subjectMany"] = "Your cart is still waiting at {0}",
        ["cart.textIntro"] = "You left a few things in your cart at {0}:",
        ["cart.textTotal"] = "Total: {0}",
        ["cart.totalLabel"] = "Total",
        ["cart.textCart"] = "Your cart: {0}",
        ["cart.textNothing"] = "Nothing has been charged, and the cart stays as you left it.",
        ["cart.heading"] = "Still in your cart",
        ["cart.lead"] = "Nothing has been charged — this is just what you left at <strong>{0}</strong>.",
        ["cart.button"] = "Open my cart",
        ["cart.footer"] = "You are getting this because you left items in your cart. The cart stays as it is — there is nothing you need to do.",

        // Приглашение оставить отзыв.
        ["invite.subjectOne"] = "How was {0}?",
        ["invite.subjectMany"] = "How were your last games?",
        ["invite.textOne"] = "You picked up {0} from {1} a week ago. If you have played it, other players would find your take useful.",
        ["invite.textMany"] = "You picked up a few games from {0} a week ago. If you have played them, other players would find your take useful.",
        ["invite.textNote"] = "A sentence is plenty. We publish reviews as they are — good and bad.",
        ["invite.textUnsubscribe"] = "Do not want these emails? {0}",
        ["invite.headingOne"] = "How was it?",
        ["invite.headingMany"] = "How were they?",
        ["invite.leadOne"] = "You picked up <strong>{0}</strong> a week ago. If you have played it, a sentence or two would help the next person decide.",
        ["invite.leadMany"] = "You picked up these a week ago. If you have played them, a sentence or two would help the next person decide.",
        ["invite.note"] = "We publish reviews as they are — good and bad. Nothing is offered in return, so your rating stays yours.",
        ["invite.rate"] = "Rate it →",
        ["invite.button"] = "Write a review",
        ["invite.footerReason"] = "You are getting this because you bought a game here.",
        ["invite.footerStop"] = "Do not ask me for reviews",

        // Восстановление доступа (простой текст).
        ["recovery.createdSubject"] = "[{0}] Account recovery requested",
        ["recovery.createdBody"] = "Someone requested access recovery (two-factor authentication reset) for your Tale Shop account.\n\nRequest: {0}\nSubmitted: {1}\nFrom IP: {2}\n\nIf this was YOU — no action is needed. Support will review the request; a reply can take up to a few days because of a mandatory waiting period.\n\nIf this was NOT you, cancel the request now:\n{3}\n\nYou can also cancel it from any device where you are still signed in (Account -> Security).\n\nTale Shop will never ask for your password or authenticator codes.",
        ["recovery.approvedSubject"] = "[{0}] Account recovery approved — waiting period started",
        ["recovery.approvedBody"] = "Your account recovery request {0} passed verification.\n\nTwo-factor authentication will be reset after: {1} (UTC)\n\nIf you did NOT request this, cancel immediately:\n{2}\n\nCancelling is also available from any signed-in device (Account -> Security).",
        ["recovery.cancelledSubject"] = "[{0}] Account recovery cancelled",
        ["recovery.cancelledBody"] = "The account recovery request {0} was cancelled and nothing was changed.\n\nIf you believe your account is being targeted, consider changing your password and reviewing active sessions in Account -> Security.",
        ["recovery.rejectedSubject"] = "[{0}] Account recovery request declined",
        ["recovery.rejectedBody"] = "Unfortunately we could not verify ownership for recovery request {0}, so it was declined.\n\nYou can submit a new request with more details (order numbers, payment information) at {1}/account-recovery.",
        ["recovery.executedSubject"] = "[{0}] Two-factor authentication was reset",
        ["recovery.executedBody"] = "Recovery request {0} was completed: two-factor authentication and backup codes were removed from your account, and all sessions were signed out.\n\nWe sent you a separate email with a link to set a new password. After signing in, please re-enable two-factor authentication in Account -> Security.\n\nIf this was NOT you, contact support immediately."
    };
}
