namespace SuperBot.WebApi.Mail;

public static partial class MailTexts
{
    private static readonly Dictionary<string, string> Pl = new()
    {
        ["date.long"] = "d MMMM yyyy",
        ["layout.tagline"] = "Tale Shop · Klucze do gier, z dostawą.",

        ["common.needHelp"] = "Potrzebujesz pomocy?",
        ["common.questions"] = "Masz pytania?",
        ["common.contactSupport"] = "Napisz do pomocy",

        ["verify.subject"] = "Potwierdź e-mail, aby otrzymać klucze — zamówienie {0}",
        ["verify.text"] = "Dziękujemy za zakup w {0}!\n\nZamówienie {1} zostało opłacone. Aby otrzymać klucze, potwierdź ten adres e-mail:\n\n{2}\n\nLink jest ważny 48 godzin. Jeśli to nie Ty składałeś zamówienie, zignoruj tę wiadomość.",
        ["verify.heading"] = "Został jeden krok",
        ["verify.lead"] = "Zamówienie {0} jest opłacone. Potwierdź ten adres e-mail, a klucze od razu trafią na tę skrzynkę.",
        ["verify.button"] = "Potwierdź e-mail i odbierz klucze",
        ["verify.footer"] = "Link jest ważny 48 godzin. Jeśli to nie Ty składałeś zamówienie, możesz spokojnie zignorować tę wiadomość.",

        ["keys.subjectPartial"] = "Część zamówienia jest gotowa — zamówienie {0}",
        ["keys.subjectSoftware"] = "Twoje klucze do programów — zamówienie {0}",
        ["keys.subjectGame"] = "Twoje klucze do gier — zamówienie {0}",
        ["keys.subject"] = "Twoje klucze — zamówienie {0}",
        ["keys.progress_one"] = "{1} z {0} klucza",
        ["keys.progress_few"] = "{1} z {0} kluczy",
        ["keys.progress_many"] = "{1} z {0} kluczy",
        ["keys.textPartial"] = "Część zamówienia {0} jest gotowa ({1}):",
        ["keys.textIntro"] = "Twoje klucze do zamówienia {0}:",
        ["keys.textSoftwareLine"] = "{0}: {1} — aktywuj na {2}",
        ["keys.textPendingHeader"] = "Jeszcze w drodze:",
        ["keys.pendingNote"] = "Wyślemy je automatycznie, gdy tylko uzupełnimy zapasy.",
        ["keys.textGuide"] = "Jak aktywować: zobacz sekcję „Klucze i aktywacja” na swoim koncie lub instrukcję na stronie.",
        ["keys.activateOn"] = "Aktywuj na {0}",
        ["keys.buttonSoftware"] = "Jak aktywować program",
        ["keys.buttonGame"] = "Jak aktywować klucz",
        ["keys.linkSoftware"] = "Aktywacja kluczy do programów",
        ["keys.headingPartial"] = "Część zamówienia jest gotowa",
        ["keys.headingMany"] = "Twoje klucze są gotowe",
        ["keys.headingOne"] = "Twój klucz jest gotowy",
        ["keys.leadPartial"] = "Zamówienie {0} — gotowe <strong>{1}</strong>. Oto, co jest już dostępne; reszta dotrze automatycznie, gdy tylko uzupełnimy zapasy.",
        ["keys.leadSoftwareMany"] = "Zamówienie {0} jest zrealizowane. <strong>Twoje klucze licencyjne są poniżej</strong> — aktywuj je u producenta, jak wskazano pod każdym kluczem.",
        ["keys.leadSoftwareOne"] = "Zamówienie {0} jest zrealizowane. <strong>Twój klucz licencyjny jest poniżej</strong> — aktywuj go u producenta, jak wskazano pod kluczem.",
        ["keys.leadMixed"] = "Zamówienie {0} jest zrealizowane. <strong>Twoje klucze są poniżej</strong> — przy każdym napisano, gdzie go aktywować.",
        ["keys.leadGame"] = "Zamówienie {0} jest zrealizowane. <strong>Twój klucz do gry jest poniżej</strong> — aktywuj go w sklepie i graj.",
        ["keys.pendingTitle"] = "Jeszcze w drodze",
        ["keys.footer"] = "Zachowaj tę wiadomość — klucz to jak gotówka. Użytego klucza nie da się odzyskać.",
        ["keys.cashbackText"] = "Cashback: +{0} ({1}%) już zmierza na Twoje saldo",
        ["keys.cashbackTextFrom"] = " i będzie dostępny od {0}.",
        ["keys.cashbackTextNow"] = " i jest już dostępny.",
        ["keys.cashbackFrom"] = "Do wykorzystania od {0}",
        ["keys.cashbackNow"] = "Do wykorzystania już teraz",
        ["keys.cashbackLink"] = "Mój cashback",
        ["keys.cashbackEarned"] = "Naliczony cashback",
        ["keys.cashbackOfOrder"] = "{0}% wartości zamówienia",
        ["place.microsoft"] = "swoim koncie Microsoft",
        ["place.app"] = "w aplikacji",
        ["place.vendor"] = "stronie producenta",

        ["autorefund.subject"] = "Zamówienie {0} zostało zwrócone — e-mail niepotwierdzony",
        ["autorefund.text"] = "Nie otrzymaliśmy potwierdzenia tego adresu e-mail w ciągu 48 godzin, dlatego zamówienie {0} zostało anulowane, a pieniądze w całości zwrócone.\n\nPieniądze wrócą na kartę, zwykle w ciągu 5–10 dni roboczych.\n\nJeśli nadal chcesz tę grę, po prostu złóż zamówienie ponownie — i od razu potwierdź e-mail.",
        ["autorefund.heading"] = "Zamówienie zwrócone",
        ["autorefund.lead"] = "Nie otrzymaliśmy potwierdzenia tego adresu e-mail w ciągu 48 godzin, dlatego zamówienie {0} zostało anulowane, a pieniądze <strong>w całości zwrócone</strong>. Wrócą na kartę, zwykle w ciągu 5–10 dni roboczych.",
        ["autorefund.button"] = "Do sklepu",
        ["autorefund.footer"] = "Nadal chcesz tę grę? Złóż zamówienie ponownie i od razu potwierdź e-mail.",

        ["refund.subjectFull"] = "Zamówienie {0} zostało zwrócone",
        ["refund.subjectPart"] = "Część zamówienia {0} została zwrócona",
        ["refund.textFull"] = "Zwróciliśmy pieniądze za zamówienie {0}.",
        ["refund.textPart"] = "Zwróciliśmy pieniądze za część zamówienia {0}. Reszta zamówienia pozostaje bez zmian.",
        ["refund.refundedList"] = "Zwrócono:",
        ["refund.refundedTitle"] = "Zwrócono",
        ["refund.backWayPaid"] = "Tą samą metodą, którą zapłacono",
        ["refund.toCard"] = "Na Twoją kartę",
        ["refund.toPaidWith"] = "Na Twoją {0}",
        ["refund.textCardArrives"] = "{0}: {1} — zwykle dociera w ciągu 5–10 dni roboczych.",
        ["refund.textPlain"] = "{0}: {1}.",
        ["refund.textCashback"] = "Na saldo cashbacku: {0} — dostępne od razu.",
        ["refund.toCashback"] = "Na saldo cashbacku",
        ["refund.underCent"] = "Kwota zwrotu jest mniejsza niż jeden cent, więc na karcie nic się nie zmieni.",
        ["refund.questions"] = "Masz pytania o zwrot? Po prostu odpowiedz na tę wiadomość.",
        ["refund.headingFull"] = "Zamówienie zwrócone",
        ["refund.headingPart"] = "Część zamówienia zwrócona",
        ["refund.cardArrives"] = "Zwroty na kartę zwykle docierają w ciągu 5–10 dni roboczych.",
        ["refund.button"] = "Mój cashback",

        ["cbnotice.availableSubject"] = "{0} cashbacku do wykorzystania",
        ["cbnotice.expiryLine"] = "Cashback jest ważny przez ograniczony czas: najwcześniejsza część wygasa {0}.",
        ["cbnotice.availableText"] = "{0} cashbacku z Twoich zamówień zakończyło okres oczekiwania i jest już na Twoim saldzie.",
        ["cbnotice.availableToSpend"] = "Do wykorzystania: {0}.",
        ["cbnotice.howToUseText"] = "Aby go użyć, włącz „Zapłać cashbackiem” przy kasie. Może pokryć całe zamówienie oprócz niewielkiego minimum płatnego kartą.",
        ["cbnotice.yourCashback"] = "Twój cashback: {0}",
        ["cbnotice.unsubscribeText"] = "Nie chcesz otrzymywać wiadomości o cashbacku? {0}",
        ["cbnotice.availableHeading"] = "Twój cashback jest gotowy",
        ["cbnotice.availableLead"] = "<strong>{0}</strong> z Twoich zamówień zakończyło okres oczekiwania i można je wykorzystać już teraz.",
        ["cbnotice.nowAvailable"] = "Do wykorzystania teraz",
        ["cbnotice.howToUseNote"] = "Włącz „Zapłać cashbackiem” przy kasie. Może pokryć całe zamówienie oprócz niewielkiego minimum płatnego kartą.",
        ["cbnotice.button"] = "Zobacz mój cashback",
        ["cbnotice.expiringSubject"] = "{0} Twojego cashbacku wygasa {1}",
        ["cbnotice.expiringText"] = "{0} Twojego cashbacku wygasa {1}. Po tej dacie kwota zostanie usunięta z salda.",
        ["cbnotice.availableNowText"] = "Do wykorzystania już teraz: {0}.",
        ["cbnotice.oldestFirstText"] = "Cashback jest zawsze wykorzystywany od najstarszego, więc każda płatność cashbackiem przed tą datą zużyje wygasającą część.",
        ["cbnotice.expiringHeading"] = "Część cashbacku wkrótce wygaśnie",
        ["cbnotice.expiringLead"] = "<strong>{0}</strong> Twojego cashbacku wygasa <strong>{1}</strong>. Po tej dacie kwota zostanie usunięta z salda.",
        ["cbnotice.expiresOn"] = "Wygasa {0}",
        ["cbnotice.availableNow"] = "Do wykorzystania teraz",
        ["cbnotice.oldestFirstNote"] = "Cashback jest wykorzystywany od najstarszego, więc płatność nim przed tą datą zużyje wygasającą część.",
        ["cbnotice.footerReason"] = "Otrzymujesz tę wiadomość, ponieważ masz saldo cashbacku w naszym sklepie.",
        ["cbnotice.footerStop"] = "Nie wysyłaj wiadomości o cashbacku",

        ["cart.subjectOne"] = "{0} wciąż czeka w Twoim koszyku",
        ["cart.subjectMany"] = "Twój koszyk wciąż czeka w {0}",
        ["cart.textIntro"] = "Zostawiłeś kilka rzeczy w koszyku w {0}:",
        ["cart.textTotal"] = "Razem: {0}",
        ["cart.totalLabel"] = "Razem",
        ["cart.textCart"] = "Twój koszyk: {0}",
        ["cart.textNothing"] = "Nic nie pobrano, a koszyk pozostał taki, jaki go zostawiłeś.",
        ["cart.heading"] = "Wciąż w koszyku",
        ["cart.lead"] = "Nic nie pobrano — to po prostu to, co zostawiłeś w <strong>{0}</strong>.",
        ["cart.button"] = "Otwórz koszyk",
        ["cart.footer"] = "Otrzymujesz tę wiadomość, ponieważ zostawiłeś produkty w koszyku. Koszyk pozostaje bez zmian — nie musisz nic robić.",

        ["invite.subjectOne"] = "Jak Ci się podobało {0}?",
        ["invite.subjectMany"] = "Jak Ci się podobały ostatnie gry?",
        ["invite.textOne"] = "Tydzień temu kupiłeś {0} w {1}. Jeśli już grałeś, Twoja opinia przyda się innym graczom.",
        ["invite.textMany"] = "Tydzień temu kupiłeś kilka gier w {0}. Jeśli już grałeś, Twoja opinia przyda się innym graczom.",
        ["invite.textNote"] = "Jedno zdanie w zupełności wystarczy. Publikujemy recenzje takie, jakie są — dobre i złe.",
        ["invite.textUnsubscribe"] = "Nie chcesz takich wiadomości? {0}",
        ["invite.headingOne"] = "Jak było?",
        ["invite.headingMany"] = "Jak Ci się podobały?",
        ["invite.leadOne"] = "Tydzień temu kupiłeś <strong>{0}</strong>. Jeśli już grałeś, zdanie lub dwa pomogą kolejnej osobie podjąć decyzję.",
        ["invite.leadMany"] = "Tydzień temu kupiłeś te gry. Jeśli już grałeś, zdanie lub dwa pomogą kolejnej osobie podjąć decyzję.",
        ["invite.note"] = "Publikujemy recenzje takie, jakie są — dobre i złe. Nic nie oferujemy w zamian, więc ocena pozostaje Twoja.",
        ["invite.rate"] = "Oceń →",
        ["invite.button"] = "Napisz recenzję",
        ["invite.footerReason"] = "Otrzymujesz tę wiadomość, ponieważ kupiłeś u nas grę.",
        ["invite.footerStop"] = "Nie proś mnie o recenzje",

        ["recovery.createdSubject"] = "[{0}] Zgłoszono odzyskiwanie dostępu",
        ["recovery.createdBody"] = "Ktoś poprosił o odzyskanie dostępu (reset uwierzytelniania dwuskładnikowego) do Twojego konta Tale Shop.\n\nZgłoszenie: {0}\nZłożone: {1}\nZ adresu IP: {2}\n\nJeśli to byłeś TY — nic nie musisz robić. Pomoc rozpatrzy zgłoszenie; odpowiedź może zająć do kilku dni ze względu na obowiązkowy okres oczekiwania.\n\nJeśli to NIE byłeś Ty, anuluj zgłoszenie teraz:\n{3}\n\nMożesz też anulować je z dowolnego urządzenia, na którym nadal jesteś zalogowany (Konto -> Bezpieczeństwo).\n\nTale Shop nigdy nie prosi o hasło ani kody z aplikacji uwierzytelniającej.",
        ["recovery.approvedSubject"] = "[{0}] Odzyskiwanie dostępu zatwierdzone — rozpoczął się okres oczekiwania",
        ["recovery.approvedBody"] = "Twoje zgłoszenie odzyskania dostępu {0} przeszło weryfikację.\n\nUwierzytelnianie dwuskładnikowe zostanie zresetowane po: {1} (UTC)\n\nJeśli NIE składałeś tego zgłoszenia, anuluj je natychmiast:\n{2}\n\nAnulowanie jest też możliwe z dowolnego zalogowanego urządzenia (Konto -> Bezpieczeństwo).",
        ["recovery.cancelledSubject"] = "[{0}] Odzyskiwanie dostępu anulowane",
        ["recovery.cancelledBody"] = "Zgłoszenie odzyskania dostępu {0} zostało anulowane i nic nie zostało zmienione.\n\nJeśli uważasz, że ktoś próbuje przejąć Twoje konto, zmień hasło i sprawdź aktywne sesje w sekcji Konto -> Bezpieczeństwo.",
        ["recovery.rejectedSubject"] = "[{0}] Zgłoszenie odzyskania dostępu odrzucone",
        ["recovery.rejectedBody"] = "Niestety nie udało nam się potwierdzić, że konto należy do Ciebie, dlatego zgłoszenie {0} zostało odrzucone.\n\nMożesz złożyć nowe zgłoszenie z dokładniejszymi informacjami (numery zamówień, dane płatności): {1}/account-recovery.",
        ["recovery.executedSubject"] = "[{0}] Uwierzytelnianie dwuskładnikowe zostało zresetowane",
        ["recovery.executedBody"] = "Zgłoszenie {0} zostało zrealizowane: uwierzytelnianie dwuskładnikowe i kody zapasowe usunięto z konta, a wszystkie sesje wylogowano.\n\nW osobnej wiadomości wysłaliśmy link do ustawienia nowego hasła. Po zalogowaniu włącz ponownie uwierzytelnianie dwuskładnikowe w sekcji Konto -> Bezpieczeństwo.\n\nJeśli to NIE byłeś Ty, natychmiast skontaktuj się z pomocą."
    };
}
