<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Riok.Mapperly" Version="4.3.1" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Hangfire.Core" Version="1.8.25" />
    <PackageReference Include="MongoDB.Driver" Version="3.12.0" />
    <PackageReference Include="Stripe.net" Version="52.4.2" />
    <PackageReference Include="Telegram.Bot" Version="22.10.3.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SuperBot.Application\SuperBot.Application.csproj" />
    <ProjectReference Include="..\SuperBot.Core\SuperBot.Core.csproj" />
  </ItemGroup>

</Project>
